remote_theme: pages-themes/minimal@v0.2.0
plugins: 
- jekyll-remote-theme
title: OSCAIL
description: This is a webpage. It can have some short description here. Or links for navigation. For example <br> <a href="https://arminstraube.github.io/oscail/members.html">List of Members</a>
logo: /assets/img/logo.png
show_downloads: true
github:
  zip_url: https://arminstraube.github.io/oscail/members.html
  another_url: https://arminstraube.github.io/oscail/members.html
